/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      animation: {
        gradient: "gradient 6s linear infinite",
      },
      keyframes: {
        gradient: {
          to: { "background-position": "200% center" },
        },
      },
      fontWeight: {
        thin: "100",
        extralight: "200",
        light: "300",
        normal: "400",
        medium: "500",
        semibold: "600",
        bold: "700",
        "extra-bold": "800",
        black: "900",
      },
      fontFamily: {
        sans: ["Overused\\ Grotesk", "sans-serif"],
        display: ["Unbounded", "Overused\\ Grotesk"],
        emblem: ["Neue Haas"],
        symbol: ["Symbols"],
      },
    },
  },
  plugins: [require("daisyui")],
  // daisyUI config (optional - here are the default values)
  daisyui: {
    themes: [
      {
        winnow: {
          primary: "#507bf2",
          "primary-focus": "#334a8a",
          "primary-content": "#ffffff",
          secondary: "#dc95ce",
          "secondary-focus": "#ab6f9f",
          "secondary-content": "#ffffff",
          accent: "#f0ccaf",
          "accent-focus": "#b89172",
          "accent-content": "#000000",
          neutral: "#2e2d2f",
          "neutral-focus": "#171618",
          "neutral-content": "#334a8a",
          "base-100": "#080b15",
          "base-200": "#0c101f",
          "base-300": "#10172b",
          "base-content": "#9fb6f7",
          info: "#66c7ff",
          success: "#87cf3a",
          warning: "#e1d460",
          error: "#ff6b6b",
        },
        levante: {
          primary: "#ffffff",
          "primary-focus": "#e6e6e6",
          "primary-content": "#000000",
          secondary: "#6491a2",
          "secondary-focus": "#324d57",
          "secondary-content": "#ffffff",
          accent: "#924d57",
          "accent-focus": "#6f3a42",
          "accent-content": "#ffffff",
          neutral: "#171618",
          "neutral-focus": "#2e2d2f",
          "neutral-content": "#80ccbf",
          "base-100": "#151a19",
          "base-200": "#2b4541",
          "base-300": "#457069",
          "base-content": "#c0f4eb",
          info: "#66c7ff",
          success: "#87cf3a",
          warning: "#e1d460",
          error: "#ff6b6b",
        },
      },
    ],
  },
};
